Repository esrg-knights/Squire, pull requests merged in 2020-09, with the labels that each got.

#58 Add names of people in activity slots while subscription is open
  activity_calendar/templates/activity_calendar/slot_blocks/normal_slot_block.html
Labels: calendar

#61 Fix/60 browser compatibility
  achievements/templates/achievements/achievement_block_user.html
  activity_calendar/static/css/fullcalendar-customisation.css
  activity_calendar/static/js/fullcalendar-init.js
  activity_calendar/templates/activity_calendar/fullcalendar.html
  core/static/css/main.css
Labels: browser support

#62 Updated Pillow to 7.2.0 (latest version)
  requirements/common.txt
Labels: security
