Repository esrg-knights/Squire, pull requests merged in 2022-03, with the labels that each got.

#258 Upgrade Pillow 9.0.1
  requirements/common.txt
Labels: security

#265 Added in-context error 500 page
  core/static/css/glitchtext.css
  core/templates/core/errors/error500.html
  core/urls.py
  core/views.py
  squire/urls.py
Labels: front-end

#269 April Fools 2022
  core/dynamic_preferences_registry.py
  user_interaction/apps.py
  user_interaction/templates/user_interaction/april_2022.html
  user_interaction/urls.py
  user_interaction/views.py
Labels: stokbrood
